#!/usr/bin/env python3
"""Generate a concise findings report for PDF reproducibility drift."""
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
    HAS_PIL = True
except ImportError:  # PIL yoksa modül import edilebilir kalır; testler SKIP
    HAS_PIL = False

OUT = Path(__file__).resolve().parent.parent / "pdf_repro_findings_deck"
W, H = 1600, 900
BG = (10, 16, 28)
PANEL = (20, 30, 48)
TEXT = (235, 242, 252)
MUTED = (155, 172, 196)
CYAN = (72, 211, 218)
RED = (255, 105, 112)
AMBER = (255, 190, 91)
GREEN = (94, 218, 151)


def font(size, bold=False):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/Library/Fonts/Arial Bold.ttf" if bold else "/Library/Fonts/Arial.ttf",
    ]
    for path in candidates:
        if Path(path).is_file():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def txt(d, xy, value, size=28, fill=TEXT, bold=False):
    d.multiline_text(xy, value, fill=fill, font=font(size, bold), spacing=10)


def slide(title, kicker, body):
    image = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(image)
    d.rectangle((0, 0, 16, H), fill=RED)
    txt(d, (90, 70), kicker.upper(), 22, RED, True)
    txt(d, (90, 110), title, 56, TEXT, True)
    d.line((90, 205, 1510, 205), fill=(45, 62, 88), width=2)
    body(d)
    txt(d, (90, 840), "LEIBNIZ2  /  PDF REPRODUCIBILITY FINDINGS", 18, MUTED, True)
    return image


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    slides = []
    slides.append(slide("The shipped PDF is behind its source", "01 / finding", lambda d: (
        txt(d, (110, 290), "Current TeX source and shipped PDF are not the same reproducible build.", 38),
        txt(d, (110, 430), "Finding", 24, RED, True),
        txt(d, (110, 475), "A source change can pass review while the delivered PDF\ncontinues to represent an earlier artifact.", 32),
        d.rounded_rectangle((1030, 300, 1430, 620), 24, fill=PANEL, outline=RED, width=3),
        txt(d, (1090, 375), "SOURCE\n≠\nSHIPPED", 48, TEXT, True),
    )))
    def experiment_body(d):
        txt(d, (110, 270), "The same input PDF was stripped repeatedly under the recorded experiment.", 32)
        rows = [("Epoch / run 1", "b090ac01…"), ("Epoch / run 2", "429984da…"), ("Epoch / run 3", "509a47a6…")]
        y = 390
        for label, value in rows:
            d.rounded_rectangle((110, y, 1430, y + 82), 16, fill=PANEL)
            txt(d, (150, y + 23), label, 27)
            txt(d, (1120, y + 23), value, 27, AMBER, True)
            y += 105
        txt(d, (110, 745), "Same raw input  →  distinct metadata-stripped hashes", 29, RED, True)
    slides.append(slide("Evidence: three epochs, three outputs", "02 / experiment", experiment_body))
    slides.append(slide("The frozen record says NON-DETERMINISTIC", "03 / diagnosis", lambda d: (
        txt(d, (110, 290), "raw SHA-256", 24, MUTED, True),
        txt(d, (110, 335), "533f00297183ac72…", 34, CYAN, True),
        txt(d, (110, 460), "verdict", 24, MUTED, True),
        txt(d, (110, 505), "NON-DETERMINISTIC", 45, RED, True),
        txt(d, (850, 340), "The metadata-stripped\nrepresentation cannot be\nfreely regenerated byte-for-byte.", 36),
    )))
    slides.append(slide("What is safe to trust", "04 / boundary", lambda d: (
        d.rounded_rectangle((110, 290, 700, 620), 24, fill=PANEL, outline=GREEN, width=3),
        txt(d, (160, 345), "AUDIT EVIDENCE", 24, GREEN, True),
        txt(d, (160, 410), "Raw PDF SHA-256\n+ committed sidecar\n+ frozen experiment record", 31),
        d.rounded_rectangle((820, 290, 1430, 620), 24, fill=PANEL, outline=AMBER, width=3),
        txt(d, (870, 345), "REBUILD RISK", 24, AMBER, True),
        txt(d, (870, 410), "Do not infer\nbyte identity from\nmetadata removal alone.", 31),
    )))
    slides.append(slide("Recommended delivery gate", "05 / action", lambda d: (
        txt(d, (110, 295), "Rebuild from current TeX with an explicit SOURCE_DATE_EPOCH.", 35),
        txt(d, (150, 420), "1. Build the package PDF\n2. Hash the rebuilt bytes\n3. Compare against the pinned sidecar\n4. Block delivery on drift\n5. Regenerate the record only after review", 31),
        txt(d, (950, 470), "DRIFT\n→ BLOCK", 52, RED, True),
        txt(d, (950, 620), "source / artifact\nrejoin the same chain", 25, MUTED, True),
    )))
    for i, image in enumerate(slides, 1):
        image.save(OUT / f"slide-{i:02d}.png")
    (OUT / "README.md").write_text(
        "# PDF reproducibility findings deck\n\n"
        "Evidence source: `qpdf_determinism_output.txt` and the package's reproducibility documentation.\n",
        encoding="utf-8")
    print(f"generated {len(slides)} slides in {OUT}")


if __name__ == "__main__":
    build()
