#!/usr/bin/env python3
"""check_tokens.py — verify design-system tokens match the dashboard.

Contracts (post-import):
1. preview.html must import design-system/tokens.css (link or @import).
2. Every custom property in tokens.css :root (dark) + [data-theme="light"]
   block appears verbatim in either the imported sheet or the HTML.
3. Every rgba tint in tokens.json must be resolvable via the token sheet
   (values kept verbatim — checked against tokens.css, not duplicated HTML).
4. The HTML must not contain a duplicate inline :root var block that would
   shadow the import (drift — two sources of truth).
5. apps/dashboard-next/app/globals.css must import design-system/tailwind.css
   (the generated Tailwind v4 bridge) and must NOT re-define any token name
   from tokens.css :root in its own :root block (shadow = drift).
6. design-system/tailwind.css :root block must equal tokens.css :root
   verbatim (the file is GENERATED by scripts/generate_tailwind.py;
   hand-edits break the bridge).
7. dashboard-next COPY DRIFT: the same walk that backs contract 5 also
   rejects (a) a token name re-declared in ANY style-rule block — a second
   :root, .dark, @media, @layer … not just the first :root the old regex
   could see, (b) a custom property whose literal value is verbatim a
   tokens.css value (a copy instead of a reference), and (c) a hard-coded
   colour literal in any custom property. Comments are stripped first, so
   prose mentioning `:root {` can neither trip nor mask a finding.
9. STRIPE TEMA VARYANTI (design-system/stripe/theme.css): meta/landing'in
   `data-theme="stripe"` varyantı GENERATED'dır. Kapı: dosya jeneratörle
   BİREBİR olmalı (elle drift yasak), tanımlar yalnız
   `:root[data-theme="stripe"]` kapsamında olmalı, jeneratörün
   REQUIRED_SLOTS'ünün tamamı bağlanmalı (eksik yuva = koyu palete sessiz
   geri dönüş), HDS ön-koşulları aynadaki (stripe/tokens.css) değerlerle
   birebir olmalı ve her yuva değeri en az bir `var(--hds-*)` referansı
   taşımalı (literal renk yasak).
8. dashboard-next PRESET BAĞIMSIZLIĞI + REFERANS KAPANIŞI: globals.css
   (a) shadcn preset CSS'i (@import "shadcn/…") DIŞARIDAN çekemez — tema
   yalnız design-system/tailwind.css köprüsünden ve repo-içi yuva
   eşlemesinden gelir, (b) stilde YAZIYLA verilmiş değer taşıyamaz (her
   custom property var()/calc() ile bağlanır; literal = kopya adayı),
   (c) her var(--X) referansı çözülebilir olmalı (tokens.css ya da aynı
   dosyada tanımlı yuva) — çürük/typo referans sessiz stil kaybıdır,
   (d) :root'ta tanımlı her renk yuvası @theme'de --color-<yuva> olarak
   yeniden sunulmalı (--radius istisna: yarıçap ölçeğini besler),
   (e) uygulama kaynağı preset-only utility (data-open: …, no-scrollbar,
   scroll-fade, shimmer) kullanamaz — preset silindiği için o sınıflar
   sessizce stilsiz kalır,
   (f) uygulama kaynağında koda gömülü RENK OLAMAZ: ne arbitrary renk
   utility'si (`bg-[#0e1116]`), ne ham hex/rgb/hsl literali (inline stil
   dahil), ne de Tailwind'ın varsayılan paleti (`bg-slate-900`,
   `text-white`) — üçü de köprü token'ını baypas eder ve temayı
   koyu/açık/stripe varyantlarında dondurur. Kapsam TÜM uygulama
   kaynağıdır (`.tsx .ts .jsx .js`) — yalnız globals.css değil,
   (g) globals.css DIŞINDAKİ her `.css` de aynı ham-renk taramasından
   geçer: yeni bir stil dosyası açmak, bir literali bu kapının dışına
   taşımanın en kolay yolu olurdu (@theme/@utility blokları burada da
   muaftır — onlar utility EŞLEMESİdir, belge custom property'si değil).

Exit 0 on match, 1 on drift.
"""
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
HTML = REPO / "_calisma" / "CIKTI" / "preview.html"
CSS = REPO / "design-system" / "tokens.css"
NEXT_GLOBALS = REPO / "apps" / "dashboard-next" / "app" / "globals.css"
NEXT_REL = "apps/dashboard-next/app/globals.css"
TAILWIND_BRIDGE = REPO / "design-system" / "tailwind.css"
STRIPE_MIRROR = REPO / "design-system" / "stripe" / "tokens.css"
STRIPE_THEME = REPO / "design-system" / "stripe" / "theme.css"
STRIPE_GEN = (REPO / "design-system" / "stripe" / "scripts"
              / "generate_stripe_theme.py")
# Varyantın tüketici yüzeyleri: tema kapsamlı override kuralları burada yaşar.
STRIPE_SURFACES = (
    REPO / "_calisma" / "CIKTI" / "preview.html",
    REPO / "_calisma" / "landing" / "landing_src.html",
)
_STRIPE_RULE = re.compile(r'\[data-theme="stripe"\]([^{}]*)\{([^{}]*)\}')
NEXT_APP = REPO / "apps" / "dashboard-next"
# shadcn preset CSS'i (shadcn/dist/tailwind.css) tarafından tanımlanan ve
# repo tarafında karşılığı OLMAYAN yüzeyler: preset importu kaldırıldığı için
# bunları kullanmak sessiz stilsizlik demektir (fail-closed denylist).
PRESET_ONLY = (
    "data-open", "data-closed", "data-checked", "data-unchecked",
    "data-selected", "data-disabled", "data-active", "data-horizontal",
    "data-vertical", "no-scrollbar", "scroll-fade", "shimmer",
)
_SOURCE_SUFFIXES = frozenset({".tsx", ".ts", ".jsx", ".js"})
_VAR_REF = re.compile(r"var\(\s*(--[\w-]+)")
# `--radius` bir renk değil: @theme'de --radius-* ölçeğini besler, --color-*
# alias'ı beklenmez.
_THEME_SLOT_EXEMPT = frozenset({"--radius"})

# Köprü utility'leri (bg-bg / text-fg / border-border) varken arbitrary RENK
# değeri kullanılamaz: `bg-[#0e1116]` token kaynağını atlar ve tema
# değişiminde (koyu/açık/stripe) donar. Kural, arbitrary değerin BAŞINDA
# literal renk arar — değerin `var()` tabanlı türetme olması serbesttir
# (shadcn'ın `bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)]`
# yuvaları tam olarak böyledir ve token'a bağlıdır).
_ARBITRARY_COLOR_UTIL = re.compile(
    r"(?<![\w-])(?:bg|text|border|ring|divide|fill|stroke|from|to|via|outline|"
    r"decoration|caret|accent|shadow)-\[\s*"
    r"(?:#[0-9a-fA-F]{3,8}|rgba?\(|hsla?\(|oklch\(\s*[\d.])"
)
# Ham renk literali (TS/TSX + globals.css): token dururken koda gömülü ton.
# `(?<!&)` HTML varlıkları (&#8212;) hex sanılmasın diye şart.
_RAW_COLOR_LITERAL = re.compile(
    r"(?<!&)#[0-9a-fA-F]{3,8}\b|(?<![\w-])(?:rgba?|hsla?)\("
)
# Tailwind arbitrary değerleri ([…]) renk taramasından önce ayıklanır:
# `shadow-[0_8px_24px_rgba(0,0,0,.5)]` sınıfın kendisi zaten token'lıdır,
# içindeki rgba koda gömülü renk DEĞİLDİR.
_ARBITRARY_VALUE = re.compile(r"\[[^\]\n]*\]")
# Tailwind'ın VARSAYILAN paleti de köprü dışı bir renk kaynağıdır:
# `bg-slate-900`/`text-white` yazmak `bg-bg`/`text-fg` yerine jeneratörden
# koparılmış sabit bir ton demektir (light/stripe varyantı donar). Ölçü
# utility'leri (border-0, ring-3) bu desene GİRMEZ: renk aileleri ton
# şartıyla (`-\d{2,3}`), yalnız white/black tonsuz aranır; `transparent` ve
# `current` (renk devralan) meşru kalır.
_NON_BRIDGE_PALETTE_UTIL = re.compile(
    r"(?<![\w-])(?:bg|text|border|ring|divide|fill|stroke|from|to|via|outline|"
    r"decoration|caret|accent|shadow)(?:-[trblxyse])?-"
    r"(?:(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|"
    r"emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)"
    r"-\d{2,3}|white|black)(?![\w-])"
)


def vars_in_block(text: str, selector_pat: str) -> dict:
    m = re.search(selector_pat + r"\s*\{(.*?)\}", text, re.S)
    if not m:
        return {}
    return {n: v.strip() for n, v in re.findall(r"(--[\w-]+)\s*:\s*([^;]+);", m.group(1))}


# Tailwind directive blocks are NOT document-level custom-property
# declarations: they compile into the `theme`/`utilities` layer and lose to
# the bridge's unlayered :root. What they hold is a utility MAPPING — e.g.
# `--font-sans: var(--font-sans)` means "the `font-sans` utility resolves to
# the repo font" — so token names and literals in there are legitimate and
# contract 7 must not flag them.
_TAILWIND_DIRECTIVES = frozenset({
    "theme", "custom-variant", "utility", "property", "keyframes",
    "plugin", "reference", "source", "variant", "apply", "config",
})

# A colour literal in a custom property = a palette that bypasses tokens.css.
_COLOR_LITERAL = re.compile(
    r"(?:^|[\s,(])(?:#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(|oklch\(|oklab\(|lab\(|lch\(|color\()"
)

_DECL = re.compile(r"^(--[\w-]+)\s*:\s*(.+)$", re.S)


def _norm_value(value: str) -> str:
    """Comparable form of a CSS value: lowercase, whitespace collapsed."""
    return re.sub(r"\s+", "", value.strip().lower())


def _is_literal(value: str) -> bool:
    """True for a written-out value (no var()/calc() indirection)."""
    return "var(" not in value and "calc(" not in value


def _css_custom_props(text: str):
    """Yield (selector_path, name, value) for every custom property in `text`.

    Comment-stripped and brace-stack driven, so unlike the `:root { ... }`
    regex this sees EVERY block (a second :root, .dark, @media, @layer …) and
    knows which selector each declaration lives in — that is what makes a
    finding actionable. Token sheets carry no `;` or `{` inside a value, so
    the scanner stays simple and dependency-free.
    """
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    stack: list[str] = []
    buf: list[str] = []

    def flush():
        raw = "".join(buf).strip()
        buf.clear()
        if not raw or not stack:
            return
        m = _DECL.match(raw)
        if m:
            yield " > ".join(stack), m.group(1), m.group(2).strip()

    for ch in text:
        if ch == "{":
            stack.append(" ".join("".join(buf).split()))
            buf.clear()
        elif ch == "}":
            yield from flush()
            if stack:
                stack.pop()
        elif ch == ";":
            yield from flush()
        else:
            buf.append(ch)


def _first_occurrence_vars(text: str) -> dict:
    """İlk-görülüm custom-property haritası (değerler normalize)."""
    out: dict = {}
    for name, value in re.findall(r"(--[\w-]+)\s*:\s*([^;{}]+?)\s*;", text):
        out.setdefault(name, re.sub(r"\s+", " ", value).strip())
    return out


def _load_stripe_generator():
    """stripe varyant jeneratörünü yol üzerinden yükle (stdlib importlib)."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("stripe_theme_gen",
                                                  STRIPE_GEN)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _stripe_variant_findings() -> list:
    """Contract 9 — GENERATED stripe tema varyantının yapısal denetimi."""
    findings = []
    if not (STRIPE_THEME.is_file() and STRIPE_GEN.is_file()):
        return ["design-system/stripe/{theme.css,scripts/generate_stripe_theme.py} "
                "eksik — stripe tema varyantı (contract 9) denetlenemedi"]

    gen = _load_stripe_generator()
    variant = STRIPE_THEME.read_text(encoding="utf-8")
    if variant != gen.render():
        findings.append(
            "design-system/stripe/theme.css jeneratörle birebir değil — "
            "yeniden üret: python3 design-system/stripe/scripts/"
            "generate_stripe_theme.py")

    blocks = list(_css_custom_props(variant))
    scopes = {selector for selector, _, _ in blocks}
    if gen.SCOPE not in scopes:
        findings.append(
            f"design-system/stripe/theme.css: {gen.SCOPE} kapsam bloğu yok")
    for selector in sorted(scopes - {gen.SCOPE}):
        findings.append(
            f"design-system/stripe/theme.css: beklenmeyen blok '{selector}' — "
            f"varyant yalnız {gen.SCOPE} altında tanımlar (global sızıntı yasak)")

    in_scope = {name: value for selector, name, value in blocks
                if selector == gen.SCOPE}
    mirror = _first_occurrence_vars(STRIPE_MIRROR.read_text(encoding="utf-8"))

    for slot in gen.REQUIRED_SLOTS:
        if slot not in in_scope:
            findings.append(
                f"design-system/stripe/theme.css: yuva {slot} bağlanmamış — "
                "eksik yuva koyu palete sessiz geri düşer")
    for name, value in sorted(in_scope.items()):
        if name.startswith("--hds-"):
            mirrored = mirror.get(name)
            if mirrored is None:
                findings.append(
                    f"design-system/stripe/theme.css: {name} aynada yok "
                    "(design-system/stripe/tokens.css)")
            elif _norm_value(value) != _norm_value(mirrored):
                findings.append(
                    f"design-system/stripe/theme.css: {name} aynadan farklı "
                    f"({value!r} != {mirrored!r})")
            continue
        if not name.startswith("--"):
            continue
        if not _VAR_REF.findall(value) or "--hds-" not in value:
            findings.append(
                f"design-system/stripe/theme.css: {name} bir --hds-* "
                f"token'ına bağlanmıyor ({value!r}) — varyant HDS kaynaklı olmalı")
        if _COLOR_LITERAL.search(_norm_value(value)):
            findings.append(
                f"design-system/stripe/theme.css: {name} renk literal'i "
                f"taşıyor ({value!r}) — HDS token'ına/türevine bağlayın")
    for name, value in sorted(in_scope.items()):
        if name.startswith("--hds-"):
            continue
        for ref in _VAR_REF.findall(value):
            if ref.startswith("--hds-") and (ref not in in_scope
                                              and ref not in mirror):
                findings.append(
                    f"design-system/stripe/theme.css: {name} çürük HDS "
                    f"referansı taşıyor (var({ref}) ne dosyada ne aynada)")

    # Yüzey tarafı: varyant kapsamlı override kuralları yalnız token tüketir
    # (krema/kağıt literalleri HDS paletini yarı-yolda keser).
    for path in STRIPE_SURFACES:
        rel = path.relative_to(REPO)
        if not path.is_file():
            findings.append(f"{rel} yok — stripe varyantı kablolaması "
                            "denetlenemedi")
            continue
        text = _strip_css_comments(path.read_text(encoding="utf-8"))
        rules = _STRIPE_RULE.findall(text)
        if not rules:
            findings.append(
                f"{rel}: `[data-theme=\"stripe\"]` override kuralı yok — "
                "tema varyantı yüzeyde karşılıksız")
            continue
        for selector, body in rules:
            where = f"{rel}: [data-theme=\"stripe\"]{selector.strip()}"
            for decl in body.split(";"):
                if ":" not in decl:
                    continue
                value = decl.split(":", 1)[1].strip()
                if not value:
                    continue
                if _COLOR_LITERAL.search(_norm_value(value)):
                    findings.append(
                        f"{where} renk literal'i taşıyor ({value!r}) — "
                        "repo token'ına bağlayın")
                if "var(" not in value:
                    findings.append(
                        f"{where} token referansı yok ({value!r})")
    return findings


def _strip_css_comments(text: str) -> str:
    """Prose is not code: contract 8 taramaları yorum-sonrası metinde koşar."""
    return re.sub(r"/\*.*?\*/", " ", text, flags=re.S)


def _strip_source_comments(text: str) -> str:
    """TSX/TS yorumlarını sil (blok + satır) — yorumdaki yüzey adı bloke etmez."""
    text = _strip_css_comments(text)
    return re.sub(r"//[^\n]*", " ", text)


def _blank_out_comments(text: str) -> str:
    """Yorumları BOŞLUKLA sil — satır numaraları korunsun diye.

    `_strip_css_comments` blok yorumu tek boşluğa indirir (satırlar kayar);
    renk taraması bulguyu `dosya:satır` diye bildirdiği için hizası şart.
    """
    text = re.sub(r"/\*.*?\*/",
                  lambda m: re.sub(r"[^\n]", " ", m.group(0)), text, flags=re.S)
    return re.sub(r"//[^\n]*", lambda m: " " * len(m.group(0)), text)


def _app_source_files(suffixes):
    """`apps/dashboard-next` altındaki kaynak dosyalar — `node_modules` ve
    `.next` AĞAÇLARINA HİÇ GİRMEDEN.

    Neden: `Path.rglob` bu iki dizini de geziyordu (ölçüldü 2026-09-28:
    `node_modules` altında tek başına 24.917 dosya → kapı ~1,4s) ve tarama
    birkaç ayrı yerde koştuğu için maliyet katlanıyordu. Kapının sözleşmesi
    zaten bu dizinlerin DIŞINI kapsar, o yüzden ağacı budamak hem doğru hem
    hızlı: ölçüm, budanmış gezinmeyle kapıyı ~0,2s'ye indiriyor.
    """
    for root, dirnames, filenames in os.walk(NEXT_APP):
        dirnames[:] = sorted(
            d for d in dirnames if d not in ("node_modules", ".next"))
        for name in filenames:
            if Path(name).suffix in suffixes:
                yield Path(root) / name


def _color_literal_findings():
    """dashboard-next kaynağında koda gömülü RENK literali arar.

    Üç kural (tema tek kaynaktan gelir: design-system köprüsü + shadcn yuvası):
      • arbitrary renk utility'si  → `bg-[#0e1116]` yerine `bg-bg`
      • ham hex/rgb/hsl literali    → `var(--token)` ya da köprü utility'si
      • Tailwind varsayılan paleti  → `bg-slate-900` yerine `bg-bg`
    Değerin token-tabanlı olması (var(), color-mix(var()…)) ihlal değildir.
    """
    findings = []
    for path in sorted(_app_source_files(_SOURCE_SUFFIXES)):
        rel = path.relative_to(REPO)
        source = _blank_out_comments(
            path.read_text(encoding="utf-8", errors="replace"))
        for lineno, line in enumerate(source.splitlines(), 1):
            hit = _ARBITRARY_COLOR_UTIL.search(line)
            if hit:
                findings.append(
                    f"{rel}:{lineno}: arbitrary renk utility'si "
                    f"({hit.group(0).strip()}) — köprü token'ını kullanın: "
                    "bg-bg / text-fg / border-border ya da var(--…) tabanlı "
                    "türetme"
                )
                continue
            pal = _NON_BRIDGE_PALETTE_UTIL.search(line)
            if pal:
                findings.append(
                    f"{rel}:{lineno}: Tailwind varsayılan palet rengi "
                    f"({pal.group(0).strip()}) — köprü token'ını kullanın: "
                    "bg-bg / text-fg / border-border (tema tek kaynaktan gelir)"
                )
                continue
            if _RAW_COLOR_LITERAL.search(_ARBITRARY_VALUE.sub(" ", line)):
                findings.append(
                    f"{rel}:{lineno}: koda gömülü renk literali — token'a "
                    "bağlayın (var(--…)); tema tek kaynaktan gelir"
                )
    # (g) globals.css'in kendi dalı aşağıda (@theme muafiyetiyle); buradaki
    # tarama panoya EKLENEN herhangi bir .css'in aynı kapıdan geçmesini
    # sağlar. Ölçüldü (2026-09-28): hex literal taşıyan yeni bir .css dosyası
    # bu dal olmadan kapıyı YEŞİL bırakıyordu — yani kural, yeni bir stil
    # dosyası açılarak sessizce atlatılabiliyordu.
    for path in sorted(_app_source_files({".css"})):
        if path == NEXT_GLOBALS:
            continue
        other_css = _blank_out_comments(
            path.read_text(encoding="utf-8", errors="replace"))
        other_exempt = _tailwind_directive_lines(other_css)
        for lineno, line in enumerate(other_css.splitlines(), 1):
            if lineno in other_exempt:
                continue
            if _RAW_COLOR_LITERAL.search(line):
                findings.append(
                    f"{path.relative_to(REPO)}:{lineno}: CSS'te koda gömülü "
                    "renk literali — token'a bağlayın (var(--…)); tema tek "
                    "kaynaktan gelir"
                )

    if NEXT_GLOBALS.exists():
        css = _blank_out_comments(NEXT_GLOBALS.read_text(encoding="utf-8"))
        exempt = _tailwind_directive_lines(css)
        for lineno, line in enumerate(css.splitlines(), 1):
            if lineno in exempt:
                continue
            if _RAW_COLOR_LITERAL.search(line):
                findings.append(
                    f"{NEXT_REL}:{lineno}: globals.css'te koda gömülü renk "
                    "literali — shadcn yuvası repo token'ına referans vermeli "
                    "(var(--…))"
                )
    return findings


def _tailwind_directive_lines(css: str):
    """`@theme`/`@utility` vb. direktif bloklarının satırları (1-tabanlı).

    Bu bloklar Tailwind'in utility NAMESPACE eşlemesidir — belge custom
    property'si değil; mevcut sözleşme de onları muaf tutuyor
    (`test_theme_block_is_exempt`). Aksi halde `@theme inline { --tw-x: … }`
    gibi meşru eşlemeler renk-literali diye kırmızıya düşerdi.
    """
    lines = css.splitlines()
    inside = False
    depth = 0
    exempt = set()
    for idx, line in enumerate(lines, 1):
        if not inside:
            if re.match(r"\s*@(theme|utility|variant|custom-variant|source|"
                        r"plugin|layer)\b", line):
                depth = line.count("{") - line.count("}")
                exempt.add(idx)
                inside = depth > 0
            continue
        exempt.add(idx)
        depth += line.count("{") - line.count("}")
        if depth <= 0:
            inside = False
    return exempt


def _in_tailwind_directive(selector_path: str) -> bool:
    for part in selector_path.split(" > "):
        part = part.strip()
        if not part.startswith("@"):
            continue
        name = part[1:].split()[0].lower() if part[1:].split() else ""
        if name in _TAILWIND_DIRECTIVES:
            return True
    return False


def main() -> int:
    html_text = HTML.read_text(encoding="utf-8")
    css_text = CSS.read_text(encoding="utf-8")

    drift = []

    # 1. import present
    has_link = bool(re.search(r'<link[^>]+href=["\'][^"\']*design-system/tokens\.css["\']', html_text))
    has_import = "design-system/tokens.css" in html_text
    if not (has_link or has_import):
        drift.append("preview.html does not import design-system/tokens.css (expected <link> or @import)")

    # Guard: no stray inline :root var block shadowing the import
    # Inline :root that defines --bg/--surface is now the single source in tokens.css
    inline_root = re.search(r"<style>.*?:root\s*\{[^}]*--bg\s*:", html_text, re.S)
    if inline_root:
        drift.append("preview.html contains an inline :root { --bg ... } block that shadows the imported tokens.css — keep vars in one place")

    # 2. tokens.css must contain both dark :root and light override
    css_dark = vars_in_block(css_text, r":root")
    css_light = vars_in_block(css_text, r':root\[data-theme="light"\]')
    if not css_dark:
        drift.append("no :root block found in design-system/tokens.css")
    if not css_light:
        drift.append('no :root[data-theme="light"] block found in design-system/tokens.css (light theme must live in tokens)')

    # Cross-check: tokens.json color keys all present in css_dark (and legacy aliases)
    import json
    tokens = json.loads((REPO / "design-system" / "tokens.json").read_text(encoding="utf-8"))
    for name, value in tokens.get("color", {}).items():
        if name == "tint":
            continue
        css_name = f"--{name}"
        if css_name not in css_dark:
            drift.append(f"tokens.json color.{name} ({value}) missing from tokens.css :root")
        elif css_dark.get(css_name) != value:
            drift.append(f"color.{name}: tokens.css {css_dark.get(css_name)!r} != tokens.json {value!r}")

    # 3. tints: values must be in tokens.css (verbatim source), not required inline in HTML
    # Normalize whitespace so "rgba(63,185,80,.15)" matches "rgba(63, 185, 80, .15)"
    def _norm_rgba(s: str) -> str:
        return re.sub(r"\s+", "", s)
    css_norm = _norm_rgba(css_text)
    for name, value in tokens.get("color", {}).get("tint", {}).items():
        if _norm_rgba(value) not in css_norm:
            drift.append(f"tint.{name} ({value}) not found in tokens.css")

    # 4. light block consistency: every preview.html var overridden in light mode must also be in tokens.css light
    # (prevents HTML light theme drifting from token sheet)
    # We compare the light block's keys against css_light
    html_light_vars = vars_in_block(html_text, r':root\[data-theme="light"\]')  # should be empty now after import
    for name in html_light_vars:
        if name not in css_light:
            drift.append(f"light var {name} present inline in preview.html but missing from tokens.css light block")

    # 5. dashboard-next must consume the generated bridge, not re-define tokens
    #    (extended by contract 7: every block, not just the first :root)
    shadowed: list[str] = []
    copies: list[str] = []
    hardcoded: dict[str, list[str]] = {}
    next_ok = NEXT_GLOBALS.exists()
    if next_ok:
        next_text = NEXT_GLOBALS.read_text(encoding="utf-8")
        # must be an actual @import statement, not just a comment mention
        has_bridge_import = re.search(
            r'@import\s+["\'][^"\']*design-system/tailwind\.css["\']', next_text
        )
        if not has_bridge_import:
            drift.append(
                "apps/dashboard-next/app/globals.css does not import "
                "design-system/tailwind.css (bridge import missing)"
            )
        token_names = set(css_dark) | set(css_light)
        # literal tokens.css value -> the names that own it (#161b22 is both
        # --surface-1 and the legacy --surface/--header-start/--code-bg)
        literal_owners: dict[str, list[str]] = {}
        for owner, value in css_dark.items():
            norm = _norm_value(value)
            if _is_literal(norm):
                literal_owners.setdefault(norm, []).append(owner)
        for selector, name, value in _css_custom_props(next_text):
            if _in_tailwind_directive(selector):
                continue
            if name in token_names:
                shadowed.append(f"{name} ({selector})")
            norm = _norm_value(value)
            if _is_literal(norm) and norm in literal_owners:
                owners = literal_owners[norm]
                copies.append(
                    f"{NEXT_REL} {selector}: {name} copies the value of "
                    f"tokens.css {', '.join(owners[:3])} "
                    f"({value.strip()}) — reference the token instead"
                )
            elif _COLOR_LITERAL.search(norm):
                hardcoded.setdefault(selector, []).append(name)
        if shadowed:
            drift.append(
                "apps/dashboard-next/app/globals.css re-defines token(s) from "
                "tokens.css :root — shadowed: "
                + ", ".join(sorted(shadowed))
            )
        drift.extend(sorted(copies))
        for selector, names in sorted(hardcoded.items()):
            shown = ", ".join(sorted(names)[:6])
            more = f" (+{len(names) - 6} more)" if len(names) > 6 else ""
            drift.append(
                f"{NEXT_REL} {selector}: {len(names)} custom propert"
                f"{'y' if len(names) == 1 else 'ies'} hard-code a colour "
                f"literal — bind them to design-system tokens (var(--...)): "
                f"{shown}{more}"
            )

    # 8. dashboard-next preset-bağımsızlığı + referans kapanışı
    if next_ok:
        next_text = NEXT_GLOBALS.read_text(encoding="utf-8")

        next_clean = _strip_css_comments(next_text)
        preset_imports = re.findall(
            r'@import\s+["\']([^"\']*(?:shadcn|preset)[^"\']*)["\']', next_clean)
        if preset_imports:
            drift.append(
                f"{NEXT_REL} imports an external preset sheet "
                f"({', '.join(sorted(set(preset_imports)))}) — token'lar ve "
                "yuva eşlemesi repo-içinde kalmalı; preset'ten bağımsız "
                "tema yalnız design-system/tailwind.css köprüsünden gelir"
            )

        local_slots = {name for selector, name, _ in _css_custom_props(next_text)
                       if not _in_tailwind_directive(selector)}
        known = set(css_dark) | set(css_light)
        theme_aliases = {name for selector, name, _ in _css_custom_props(next_text)
                         if _in_tailwind_directive(selector)
                         and "theme" in selector}

        for selector, name, value in _css_custom_props(next_text):
            if _in_tailwind_directive(selector):
                continue
            norm = _norm_value(value)
            specific = (_COLOR_LITERAL.search(norm) or norm in literal_owners)
            if _is_literal(value) and not specific:
                drift.append(
                    f"{NEXT_REL} {selector}: {name} yazıyla verilmiş değer "
                    f"taşıyor ({value.strip()}) — kopya yerine repo "
                    "token'ına referans verin (var(--...))"
                )

        for ref in sorted(set(_VAR_REF.findall(next_clean))):
            if ref not in known and ref not in local_slots:
                drift.append(
                    f"{NEXT_REL}: var({ref}) çözülemiyor — ne "
                    "design-system/tokens.css'te ne de dosyanın kendi "
                    "yuva bloğunda tanımlı (çürük referans)"
                )

        for name in sorted(local_slots - _THEME_SLOT_EXEMPT):
            if f"--color-{name[2:]}" not in theme_aliases:
                drift.append(
                    f"{NEXT_REL}: :root yuvası {name} @theme'de "
                    f"--color-{name[2:]} olarak yeniden sunulmamış — "
                    "utility'ler (bg-*/text-*) bu yuvaya bağlanamaz"
                )

        preset_hits = []
        for path in sorted(_app_source_files(_SOURCE_SUFFIXES)):
            source = _strip_source_comments(
                path.read_text(encoding="utf-8", errors="replace"))
            for lineno, line in enumerate(source.splitlines(), 1):
                for token in PRESET_ONLY:
                    if re.search(rf"(?<![\w-]){re.escape(token)}(?![\w-])", line):
                        preset_hits.append(
                            f"{path.relative_to(REPO)}:{lineno} ({token})")
        if preset_hits:
            shown = ", ".join(preset_hits[:5])
            more = f" (+{len(preset_hits) - 5} more)" if len(preset_hits) > 5 else ""
            drift.append(
                "dashboard-next kaynağı preset-only yüzey kullanıyor "
                f"(shadcn/tailwind.css importu YOK): {shown}{more} — "
                "karşılığını design-system köprüsüne/repo CSS'ine ekleyin"
            )

        # (f) renk literali sızması: `bg-[#0e1116]` / gömülü hex, köprü
        # utility'lerini (bg-bg, text-fg, border-border) baypas eder ve temayı
        # dondurur. Aynı sınıf: 2026-09-19 tailwind-design-system turunda
        # temizlendi, kapı olmadığı için geri gelebilirdi.
        colour_hits = _color_literal_findings()
        if colour_hits:
            shown = ", ".join(colour_hits[:5])
            more = f" (+{len(colour_hits) - 5} more)" if len(colour_hits) > 5 else ""
            drift.append(
                "dashboard-next kaynağında koda gömülü renk değeri var: "
                f"{shown}{more} — köprü token'ı kullanın (bg-bg / text-fg / "
                "border-border); tema tek kaynaktan gelir"
            )

    # 9. stripe HDS tema varyantı (GENERATED) — kapsam + referans kapanışı
    drift.extend(_stripe_variant_findings())

    # 6. the generated bridge must stay verbatim-equal to tokens.css :root
    bridge_root = (
        vars_in_block(TAILWIND_BRIDGE.read_text(encoding="utf-8"), r":root")
        if TAILWIND_BRIDGE.exists()
        else {}
    )
    if bridge_root != css_dark:
        drift.append(
            "design-system/tailwind.css :root != tokens.css :root — regenerate: "
            "python3 design-system/scripts/generate_tailwind.py"
        )

    if drift:
        print("TOKEN DRIFT:")
        for line in drift:
            print(f"  {line}")
        return 1
    clean = next_ok and not (shadowed or copies or hardcoded)
    stripe_slots = 0
    if STRIPE_THEME.is_file() and STRIPE_GEN.is_file():
        stripe_slots = len(_load_stripe_generator().REQUIRED_SLOTS)
    print(f"OK — import present, tokens.css :root {len(css_dark)} + light {len(css_light)} vars, "
          f"{len(tokens['color']['tint'])} tints in sheet, "
          f"dashboard-next bridge+copy-drift {'OK' if clean else 'n/a'}"
          f" (preset-bağımsız + referans-kapalı + renk-kaynağı-temiz), "
          f"stripe HDS varyantı {stripe_slots} yuva jeneratörle birebir")
    return 0


if __name__ == "__main__":
    sys.exit(main())
